project:
  type: website
  resources:
    - data_shared/*.csv
  output-dir: docs
  render:
    - "*.qmd"
    # - "modules/*.qmd"
    - "!presentations/lbspr.qmd" # Exclude this specific file

website:
  # title: "Fishery Stock-SOMALIA"
  navbar:
    logo: images/coat_OG_web.png
    background: secondary
    left:
      - text: "Training"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Program"
        href: schedule.qmd
      - text: "Modules"
        menu:         
          - text: "Module 1: Stock Assessment Fundamentals & Concepts"
            href: modules/module1.qmd
          - text: "Module 2: Data Collection Protocols & Sampling Design"
            href: modules/module2.qmd
          - text: "Module 3: Data-Limited Stock Assessment Methods"
            href: modules/module3.qmd
          - text: "Module 4: Data Processing and Storage"
            href: modules/module4.qmd
          - text: "Module 5: Data Analysis Methods for Stock Assessment"
            href: modules/module5.qmd
          - text: "Module 6: Practical Field Exercises at Landing Sites"
            href: modules/module6.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Presentations"
        menu: 
      #     - text: "Stock Assessment Fundamentals & Concepts"
      #       href: presentations/module_1_presentation.qmd
      #     - text: "Data Collection Protocols & Sampling Design"
      #       href: presentations/module_2_presentation.qmd
      #     - text: "Data-Limited Stock Assessment Methods"
      #       href: presentations/module_3_presentation.qmd
      #     - text: "Data Processing and Storage"
      #       href: presentations/module_4_presentation.qmd
      #     - text: "Data Analysis Methods for Stock Assessment"
      #       href: presentations/module_5_presentation.qmd
      #     - text: "Practical Field Exercises at Landing Sites"
      #       href: presentations/module_6_presentation.qmd
          - text: "Training Need Assessment"
            href: presentations/tna_presentation.qmd
          - text: "Stock fundamentals"
            href: presentations/module1_stock_fundamentals.qmd
          - text: "Data type"
            href: presentations/module1_data_req_slides.qmd
          # - text: "Trophic level"
          #   href: presentations/presentation_10_trophic_level.qmd
          # - text: "Fecundity"
          #   href: presentations/presentation_11_fecundity_maturity.qmd
          - text: "Length-based model framework"
            href: presentations/presentation_12_lbspr2.qmd
          - text: "Length Frequency & Maturity"
            href: exercises/maturity.qmd
      - text: "Resources"
        menu:
          - text: "Resources1: The Giant Fishery Report"
            href: resources/resource1.qmd
      - text: "Exercises"
        menu:
          - text: "Install Tools"
            href: exercises/steps_for_tools.qmd
          - text: "Determine maturity"
            href: exercises/maturity_exercise.qmd
          - text: "Length Frequencies"
            href: exercises/lfq.qmd
          - text: "Size Separation and  maturity"
            href: exercises/size_maturity.qmd
          - text: "Estimate stock"
            href: exercises/estimate_stock_lbspr.qmd
          - text: "Estimate stock yellowfin"
            href: exercises/estimate_stock_lbspr_yft.qmd





    right:
      - icon: github
        href: https://github.com/lugoga/stock_training_somalia

  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Getting Started"
        contents:
          - index.qmd
      - section: "Course Modules"
        contents:
          - modules/module1.qmd
          - modules/module2.qmd
          - modules/module3.qmd
          - modules/module4.qmd
          - modules/module5.qmd
          - modules/module6.qmd

  page-footer:
    background: secondary
    # left: |
    #   © 2025 Semba      
    center: |
      © 2025 Semba | Developed in partnership with [TAFIRI](https://www.tafiri.go.tz). | [Contact Us](mailto:info@tafiri.go.tz)
    # right: |
    #   [Contact Us](mailto:info@tafiri.go.tz) | [GitHub]({{< var website.navbar.right.1.href >}})

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: false
bibliography: references.bib